src/utils/cn.ts, src/utils/supabase/check-env-vars.ts, src/utils/supabase/client.ts, src/utils/supabase/middleware.ts, src/utils/supabase/server.ts, src/utils/utils.ts
This pull request introduces the foundational setup for integrating Supabase with our Next.js application.
- Integrated Supabase with the Next.js framework.
=> work on supabase basic structure

src/app/globals.css, src/common/StandardPage/StandardPage.test.tsx, src/common/StandardPage/StandardPage.tsx, tailwind.config.ts
This PR address a new feat in which i have created a common component `standarpage` that will appare when list emputy 
- created component `StandardPage.tsx`
- write test
=> feat(ticket #131): create a standard page

.github/pull_request_template.md
This pull requset make change in `pull_request_template.md` file where i have update descriptions
=> fix(ticket # 135): Updated Pull Request Template

src/app/attendance/actions/create-attendance.ts, src/app/attendance/actions/createAttendance.test.tsx, src/app/attendance/components/AttendanceFormBuilder.tsx, src/app/attendance/components/attendanceFormBuilder.test.tsx, src/common/MemberSelector/MemberSelector.tsx, src/types/index.tsx
This PR introduces a common member selector component based on the logged-in user. It is built on top of `Shadcn`, `React Hook Form`, and `Zod Validation`. It avoid the duplication of role base member selection functionality.
* The component will be utilized in both the `Attendance Form Builder` and `Leave Form Builder`.
=> feat(ticket#141): Common Member Selector

src/app/attendance/actions/getAttendance.ts, src/app/attendance/components/AttendanceList.tsx, src/app/attendance/page.tsx, src/app/members/components/MemberActionRender.tsx, src/lib/db.tsx, src/types/index.tsx
* Create Attendance list and show all attendance 
I've added temporary table action, but will create a separate ticket for this soon. also create ticket for DateRange filter to the Attendance table, set to last 30 days, and a CommonMemberSelector filter to the Attendance table.
=> Create Attendance list

src/app/attendance/actions/getAttendance.ts, src/app/attendance/actions/getAttendanceById.ts, src/app/attendance/add/page.tsx, src/app/attendance/components/AttendanceActionRender.tsx, src/app/attendance/components/AttendanceFormBuilder.tsx, src/app/attendance/components/attendanceFormBuilder.test.tsx, src/app/attendance/edit/[id]/page.tsx, src/lib/routes.tsx
* Get attendance by userId and fill her data into form
https://github.com/user-attachments/assets/3278fe2f-0312-4754-aea3-70f54bf9620e
=> get attandance user by Id & and show data in form

src/middleware.ts
This PR addresses an issue with the middleware.
=> fix : Refixed Middleware conditon

src/app/attendance/actions/update-attendance.ts, src/app/attendance/add/page.tsx, src/app/attendance/components/AttendanceActionRender.tsx, src/app/attendance/components/AttendanceFormBuilder.tsx, src/app/attendance/components/AttendanceList.tsx, src/app/attendance/components/attendanceFormBuilder.test.tsx, src/app/attendance/edit/[id]/page.tsx, src/app/leaves/add/page.tsx, src/app/leaves/components/LeaveBreadcrumbs.tsx, src/app/leaves/components/LeavesHeader.tsx, src/app/leaves/page.tsx, src/app/members/components/MemberHeader.test.tsx, src/app/members/components/MemberList.test.tsx, src/app/members/components/MemeberHeader.tsx, src/common/MemberSelector/MemberSelector.tsx, src/common/NavigationButton.tsx, src/lib/routes.ts, src/utils/utils.ts
This PR introduces the Leave Header component, which includes the following key elements:
* **Breadcrumb Navigation:** Provides a clear path for users to navigate back to previous sections or the main page.
* **Search Bar:** Allows users to search for specific leave requests
* **`Add Leave Request` Button:** A button that enables users to create a new leave request.
=> feat(ticket#218): Implement Leave Header with Breadcrumb, Search Bar, and "Add Leave Request" Button

src/app/layout/components/Sidebar.tsx
- Fixed member is not display in the sidebar
=> Fixed minor member issue

src/app/(dev)/playground/actions/add-dev-user.ts, src/app/(dev)/playground/actions/update-dev-user-role.ts, src/app/(dev)/playground/components/AddDevUserForm.tsx, src/app/(dev)/playground/components/UpdateDevUserForm.tsx
This PR addressing a minor update in `dev page` i have added `name` field , navigation and updating cookies on role update
- dynamic dates 
- added navigation on new user add
=> Fix(ticket#241) : Improvements  In Dev Page

src/app/(dev)/playground/components/AddDevUserForm.tsx, src/app/(dev)/playground/components/UpdateDevUserForm.tsx, src/app/(dev)/playground/page.tsx
Wrap form with card component in dev page for better look
=> Added card

src/app/globals.css, src/app/layout/components/Sidebar.tsx, tailwind.config.ts
This includes the implementation of active sidebar items. Any sidebar item will be marked as active when its path matches the current route's pathname.
=> fix(ticket#248): Active Sidebar Item Implementation

src/app/(app)/attendance-report/actions/attendance-report.ts, src/app/(app)/attendance-report/components/AttendanceReport.tsx, src/app/(app)/attendance-report/page.tsx, src/constant/constant.ts
- Create Server action for monthly attendance report
- Bind attendance report table with real data
=> feat(ticket#43):Create attendance report action

src/app/(app)/missing-shoes/add/page.tsx, src/app/(app)/missing-shoes/page.tsx
This PR includes  build error solution for main
=> Fix : Build Error

package.json, src/app/(app)/attendance-report/actions/attendance-report.ts, src/app/(app)/leaves/actions/get-leave-request-by-date.ts, yarn.lock
- Create a server action to get all leave records and filter them to display the count of approved leaves in a column
- Also improve scenario & some more minor things
=> Feat(ticket#257): Create leave server action

src/app/(app)/missing-shoes/actions/get-missing-shoe-by-id.ts, src/app/(app)/missing-shoes/components/MissingShoesReportDetails.tsx, src/app/(app)/missing-shoes/details/[id]/page.tsx
This PR includes a server action to retrieve the details of missing shoes and their owners based on the missing shoe Id.
*  `get-missing-shoe-by-id.ts` contains server actions to get missing shoe details by id.
* `MissingShoesReportDetails.tsx`
https://www.loom.com/share/d1822eb99f9d4a42828df41e82cc9acd?sid=944c9850-0c91-48fa-ae5e-733f3609eac5
=> feat(ticket#272) Implement getMissingShoeDetailsById Server Action

src/app/(app)/missing-shoes/actions/get-missing-shoe-by-id.ts, src/app/(app)/missing-shoes/add/components/MissingShoesActions.tsx, src/app/(app)/missing-shoes/components/MissingShoesReportDetails.tsx, src/app/(app)/missing-shoes/details/[id]/page.tsx, src/lib/routes.ts
This PR includes the UI design for the missing shoe report. The report displays shoe details such as status, shoe token, time lost, and a description of the shoe. It also includes the shoe owner's information, including their name, phone number, and address.
- **MissingShoesReportDetails.tsx** contains the UI design for the missing shoe report.
- **MissingShoesActions.tsx** handles the action for viewing details.
- **routes.ts** defines the routes for viewing details.
=> feat(ticket#273): Missing Shoe Report UI Design

src/app/(app)/missing-shoes/actions/process-missing-shoe-status.ts, src/app/(app)/missing-shoes/add/components/MissingShoesActions.tsx
This PR contains a server action that updates the status of missing shoes. There are two possible statuses for a missing shoe: `missing` and `found`.
* `process-missing-shoe-status.ts` contains server action to update missing shoe status
* `MissingShoesActions.tsx`   handle the missing shoe update action
https://www.loom.com/share/034e9d2375414500b4fc3cb91c3d3091?sid=863dd111-0b2f-4129-b5c3-ec061cf23e3f
=> feat(ticket#277): Implementation of missing shoe status process

src/app/(app)/attendance/components/AttendanceHeader.tsx, src/app/(app)/layout.tsx, src/app/(app)/leaves/components/LeavesHeader.tsx, src/app/(app)/members/components/MemberHeader.tsx, src/app/(app)/missing-shoes/components/MissingShoesHeader.tsx, src/app/(dev)/playground/actions/add-dev-user.ts, src/app/layout/components/Sidebar.tsx, src/common/HeaderWapper/HeaderWrapper.tsx, src/common/StatusBar/index.tsx
This PR addressing a feat in which showing a alertbar that show untill new user not change his password , and updated header , all common logics i have moved into new componet `HeaderWapper`
- Alertbar.tsx
- HeaderWapper.tsx
=> feat(tick #266): added alertbar

src/app/(app)/missing-shoes/actions/get-missing-shoe-by-id.ts, src/app/(app)/missing-shoes/actions/update-missing-shoe-details.ts, src/app/(app)/missing-shoes/add/components/MissingShoesActions.tsx, src/app/(app)/missing-shoes/add/components/MissingShoesFormBuilder.tsx, src/app/(app)/missing-shoes/edit/[id]/page.tsx, src/lib/routes.ts
This PR contains the functionality to edit missing shoe details. It allows for the editing of all related entities using the unique ID of the missing shoe.
* `update-missing-shoe-details.ts`  contain server action that update missing shoe details
* `MissingShoesActions.tsx` handle menu action that navigate to `/missing-shoe/edit/:id`
https://www.loom.com/share/174009afaa5b4e8d8364be9ff28b5d21?sid=ebf2a02a-a226-4ff6-90a8-f3e2b233d304
=> feat(ticket#282): Implementation of Missing Shoe Edit Details

src/app/(app)/missing-shoes/components/MissingShoes.tsx
This PR fixes a minor issue related to the missing shoe status update.
- `MissingShoes.tsx` displays missing shoe data in a TanStack table.
https://www.loom.com/share/3664553c9d4e496eaaf8bc83e0e4d5b3?sid=8e7a4fa4-0dbe-4f06-acea-466bd626fd8f
=> fix(ticket#297): Missing Shoe Status Update Issue

src/app/(app)/attendance/components/AttendanceHeader.tsx, src/app/(app)/members/details/[id]/page.tsx
This PR addressing a minor UI fixes in breadcrumbs and navigation on in header.
=> fix(ticket #291): UI minor fix

src/app/(app)/attendance/edit/[id]/page.tsx, src/app/(app)/attendance/page.tsx, src/app/(app)/leaves/add/page.tsx, src/app/(app)/leaves/edit/[id]/page.tsx, src/app/(app)/leaves/page.tsx, src/app/(app)/members/add/page.tsx, src/app/(app)/members/edit/[id]/page.tsx
This PR fixes the inconsistent formatting of header titles across the project to ensure consistency.
=> Fix(ticket#257): Header Titles Formatting 

src/app/(app)/missing-shoes/add/page.tsx, src/app/(app)/missing-shoes/details/[id]/page.tsx, src/app/(app)/missing-shoes/edit/[id]/page.tsx, src/app/(app)/missing-shoes/page.tsx
This PR implements the missing shoes management header, which includes breadcrumbs based on the route structure and an **Add Shoe** button on the `/missing-shoes` route.
The following routes contains header
- `/missing-shoes/add`
- `/missing-shoes/edit/:id`
- `/missing-shoes/details/:id`
=> feat(ticket#288): Implementation of the missing shoes management header

src/app/(app)/funds/actions/get-all-funds.tsx, src/app/(app)/funds/components/FundsList.tsx, src/app/(app)/funds/page.tsx, src/types/index.tsx
Get All funds and integrate with the front end 
* create a `get-all-funds` function
* integrate with the front end
=> feat(ticket#323): Get All Funds

src/app/(app)/attendance/add/page.tsx, src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/attendance/edit/[id]/page.tsx, src/app/(app)/funds/add/page.tsx, src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(app)/funds/edit/[id]/page.tsx, src/app/(app)/leaves/add/components/LeaveRequestFormBuilder.tsx, src/app/(app)/leaves/edit/[id]/page.tsx, src/common/Filter/Filter.tsx, src/common/Filter/LeaveFilter.tsx, src/common/MemberSelector/MemberSelector.tsx
This PR fixes the member selector issue caused by retrieving login user data from the root server component.
https://www.loom.com/share/ea4d74f8fc204d38a572246738f3edbd?sid=805e4727-e8c5-4344-879a-207054e7c481
=> Fix (Ticket #328): Resolved Member Selector Issue

src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/leaves/components/LeavesRequestList.tsx, src/app/(app)/members/components/MemberList.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/app/(app)/missing-shoes/components/MissingShoesHeader.tsx, src/common/StandardPage/StandardPage.tsx
- Added new icon prop in standard page
=> Feat(Ticket#311): Standard prop icon

src/app/(app)/members/components/MemberActionRender.tsx, src/app/(app)/members/components/MemberDetails.tsx, src/app/(app)/members/components/MemberFormBuilder.tsx, src/app/(app)/members/components/MemberHeader.tsx, src/app/(app)/members/details/[id]/page.tsx, src/common/HeaderWapper/HeaderWrapper.tsx, src/common/NavigationButton.tsx, src/components/ui/datepicker.tsx, src/components/ui/input.tsx
Remove Aligment issue 
* added padding in `HeaderWrapper`
*
=> Removed Aligment issues

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/attendance/edit/[id]/page.tsx
- fix timing issue in edit case of attendance
* updated returning data in edit route
=> Fixed Attendance Edit Case

src/app/(app)/funds/components/FundsHeader.tsx, src/app/(app)/funds/components/FundsList.tsx
This PR adds a search functionality that locally searches based on the user's submitted fund.
https://www.loom.com/share/e40c13fab1c44886a55ca4d30d58696e?sid=04513472-cacf-44f1-ab6e-7f91bc7fa17c
=> feat(ticket#338) Implementation of search bar for funds

src/app/(app)/missing-shoes/actions/create-missing-shoes-report.ts, src/app/(app)/missing-shoes/actions/get-all-missing-shoes.ts, src/app/(app)/missing-shoes/actions/get-missing-shoe-by-id.ts, src/app/(app)/missing-shoes/actions/update-missing-shoe-details.ts, src/app/(app)/missing-shoes/components/MissingShoesHeader.tsx, src/app/(app)/missing-shoes/components/MissingShoesReportDetails.tsx, src/app/(app)/missing-shoes/page.tsx, src/types/index.tsx
- This PR adds search functionality for missing shoes. 
- It implements search via query params and includes the `Reported By` at server action for both adding and updating records,
- `Reported By` is also displayed in the missing shoe report details.
https://www.loom.com/share/cdb142ec84fa4134a3ed7974334c7890?sid=ec830aee-fe0e-484c-9590-52765c3fb9fa
=> Fix (Ticket #330): Add Search Functionality and Reported By Field to Missing Shoe Report

src/app/(app)/loading.tsx, src/app/(app)/members/components/MemberList.tsx
This PR addressing a bug fix where i have added the `loading.tsx`
- `loading.tsx`
=> fix(ticket#345): added loader

src/app/(app)/members/components/MemberDetails.tsx, src/common/Avatar/UserAvatar.tsx
work on avatar text and alignment of status
* changed the text of the avatar and also updated the alignment of the status
=> changed avatar text

src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(auth)/login/actions/loginUser.ts, src/app/(auth)/login/components/Login.tsx, src/app/layout/components/Sidebar.tsx, src/middleware.ts
remove notification,attendance report and dashboard routes
* comment all unused routes 
* update middleware according to it
=> Removed Unused Routes

src/app/(auth)/login/actions/loginUser.ts, src/app/(auth)/login/components/Login.tsx
- Add a check to ensure that deactivated users are not able to log in.
=> feat(Ticket#349):Added deactivated user validation

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(app)/leaves/add/components/LeaveRequestFormBuilder.tsx, src/app/(app)/members/components/MemberFormBuilder.tsx, src/app/(app)/missing-shoes/add/components/MissingShoesFormBuilder.tsx, src/app/(auth)/login/components/Login.tsx, src/app/(dev)/playground/components/AddDevUserForm.tsx, src/app/(dev)/playground/components/UpdateDevUserForm.tsx, src/middleware.ts
This PR addressing a minor fix UI concern , where i have updated middleware matcher and enable forms button by default
=> fix(ticket#354): middleware matcher and button default state issue fixed

src/app/(app)/attendance/components/AttendanceActionRender.tsx, src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/leaves/components/LeaveActionRender.tsx, src/app/(app)/leaves/components/LeavesRequestList.tsx, src/middleware.ts, yarn.lock
=> fixed(ticket#353) actions of leaves

src/common/DateRangePicker/DateRangePicker.tsx
Fixed date picker is not fully visible in the Add Leave Request form.
=> Fixed date picker is not fully visible issue

src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/funds/components/FundsList.tsx, src/app/(app)/leaves/components/LeavesRequestList.tsx, src/app/(app)/members/components/MemberList.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/app/layout/PageLayout.tsx, src/common/Filter/AttendanceFilter.tsx, src/common/Filter/LeaveFilter.tsx, src/common/FormWrapper.tsx, src/common/HeaderWapper/HeaderWrapper.tsx
Change the padding issue of layout in the case of mobile responsiveness and also fixed column width issue 
* changed padding of the layout 
* changed the width of the column in the app so that name should be shown in one line 
* changed the text sentence of the heading of the column
=> Fixed Padding and column Width issue

src/app/layout/components/Sidebar.tsx
Fixed funds & attendance report tabs take time to load in side bar
=> Fixed some side bar items take time to load

src/app/(app)/attendance/components/AttendanceActionRender.tsx, src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/attendance/page.tsx, src/app/(app)/leaves/components/LeaveActionRender.tsx, src/app/(app)/leaves/components/LeavesRequestList.tsx, src/app/(app)/leaves/page.tsx, src/common/Filter/LeaveFilter.tsx
remove unnecessary rendering issue in leave and attendance routes
* removed userUser hook in these routes
=> Removed unnecessary rendering

src/app/(auth)/login/components/Login.tsx
- Fixed login phone number validation error message
=> Fixed login validation error message

package.json, src/app/(app)/attendance/components/attendanceFormBuilder.test.tsx, src/common/Filter/AttendanceFilter.tsx, src/common/Filter/LeaveFilter.tsx, src/common/Loader/Loader.tsx, src/common/MemberSelector/MemberSelector.tsx, yarn.lock
This PR addressing a fix in which i have added loader in `MemberSelector.tsx` component.
=> fix: added loader in member selector

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx
This PR resolve  the issue with the user name in the Attendance edit case.
=> fix(ticket#369): Resolve issues with attendance editing

src/app/(app)/funds/components/FundsHeader.tsx, src/app/(app)/members/components/MemberHeader.tsx, src/app/(app)/missing-shoes/components/MissingShoesHeader.tsx, src/common/HeaderWapper/HeaderWrapper.tsx, src/common/SearchBox/SearchBox.tsx
This PR fixes the responsive search bar by ensuring it expands smoothly in width and centers the search icon on smaller screens.
https://www.loom.com/share/430996f050f742a6a87a87c70ea7a781?sid=578eb59d-a035-4456-81e9-a88bec04c8f8
=> fix(ticket#367): Resolve issue with responsive search bar

src/app/(app)/members/components/MemberList.tsx, src/app/(app)/members/page.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/app/layout/components/Sidebar.tsx, src/common/DateRangePicker/DateRangePicker.tsx
Fixed Not found not show when search query not match in missing shoes & members list 
https://github.com/user-attachments/assets/f47cb1b5-4fff-422a-9f9d-b28fd94b1986
=> Fixed not found not show when search query not match

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/attendance/modal/AttendanceDetails.tsx, src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(app)/leaves/add/components/LeaveRequestFormBuilder.tsx, src/app/(app)/leaves/modal/LeaveRequestDetails.tsx, src/app/(app)/members/components/MemberFormBuilder.tsx, src/app/(app)/missing-shoes/add/components/MissingShoesFormBuilder.tsx, src/app/(auth)/login/components/Login.tsx, src/app/(dev)/playground/components/AddDevUserForm.tsx, src/common/Loader/Loader.tsx
Add loader on the button during form submit 
* added loader during form submit
=> Fixed loader issue

src/app/(app)/layout.tsx, src/app/layout/components/Sidebar.tsx, src/common/HeaderWapper/HeaderWrapper.tsx
=> Removed setting from side bar

src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/leaves/components/LeavesRequestList.tsx, src/common/NoDataFound.tsx
Add No Data Found in case of no leave or attendance found
* Create common component `NoDataFound` 
* use this when no leave or attendance found
=> Added No Data Found Text

src/app/(app)/members/components/MemberActionRender.tsx, src/app/(app)/members/components/MemberList.tsx, src/common/ActionMenu/ActionsMenu.tsx, src/common/SearchBox/SearchBox.tsx
- Remove shift column from the member list
- update member list according to roles
- add extra padding in the search bar
- update text of actions
- - Removed shift column from the member list
- updated member list according to roles
- added extra padding in the search bar
- updated text of actions
=> Removed unnecessary column and updates text

src/app/(app)/leaves/actions/createLeaveRequest.ts, src/app/(app)/leaves/actions/updated-leave-request.ts, src/app/(app)/leaves/add/components/LeaveRequestFormBuilder.tsx, src/app/(app)/leaves/components/LeaveActionRender.tsx, src/app/(app)/leaves/components/LeaveRequestDetails.tsx, src/app/(app)/leaves/details/[id]/page.tsx, src/common/DateRangePicker/DateRangePicker.tsx, src/common/Filter/MemberFilter.tsx, src/components/ui/textarea.tsx, src/lib/routes.ts
- **Fixed Date Validation:** Resolved the "undefined" error occurring during date validation.
- **Improved Reason for Leave Input:** Updated the Reason for Leave field to render on blur state, preventing errors while typing.
- **Replaced Modal with Page:** Changed the Leave Request Detail to render as a full page instead of a modal.
https://www.loom.com/share/8765fe5bf43141d9a48266a67db574bd?sid=486d1156-d13e-4b47-8827-bb0e67251c7e
=> fix(ticket#408): Leave request fixes

src/app/(app)/attendance/components/AttendanceActionRender.tsx
Fixed attendance row not deleted in real time issue
=> Attendance row not delete in real time

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx
- Fixed user name dropdown error in attendance edit form 
- **Error:** expected string, received number
=> Fixed user name dropdown error

src/common/NavigationButton.tsx
Fixed Add button text align issue
=> Fixed button text align issue

src/app/(app)/missing-shoes/add/components/MissingShoesActions.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/common/ConfirmationModal/ConfirmationModal.tsx, src/components/ui/dialog.tsx
This  PR resolve missing shoes status issue by adding a confirmation modal to confirm if the shoes are found, then update the status. No further status updates required.
https://www.loom.com/share/4adfbd57f08e4f8fa0c8cf92300f4626?sid=13b706ec-3a45-4d4d-8ea0-3f0516b338d8
=> fix(ticket#418): Resolved issues with missing shoes status

src/app/(auth)/login/actions/loginUser.ts, src/app/(auth)/login/components/Login.tsx
This PR addressin minor bug fixes where is have fixed following errors;
- login page Error message fix on production
- EyeIcon Size
- Phone Number `Error Message`
=> fix:login page Error message fix on production 

src/app/(app)/funds/actions/update-fund-details.ts, src/app/(app)/funds/add/page.tsx, src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(app)/funds/components/FundsList.tsx, src/app/(app)/funds/page.tsx, src/app/layout/components/Sidebar.tsx
- **Hide Funds Sidebar:** Funds sidebar item is now hidden for members and shift incharge.
- **Fix Route After Fund Update:** Success message now triggers correct route change.
- **Amount Input Validation:** Amount field now accepts only numeric values.
https://www.loom.com/share/c3aeed08d7394a1eaa2c6e4ec9c05ded?sid=695f1b92-b772-4144-ae5b-096747ee5106
=> fix(ticket#422): Resolved issues in the funds module

src/app/(app)/attendance/components/AttendanceActionRender.tsx, src/common/ConfirmationModal/ConfirmationModal.tsx, src/constant/constant.ts
Add confirmation model & also added conditions on in action menu options on  stats base
=> Add confirmation model & condtion on stats base

src/common/SearchBox/SearchBox.tsx
- Fix search bar UI issues: ensure it expands fully and close expanded search bar on navigation.
-  `SearchBox.tsx`
https://www.loom.com/share/af3d5917f69b4753a024c1dfe7e98945?sid=7d6ac322-7589-4e5d-9f53-899cf782470f
=> fix(ticket # 412): Resolve search bar UI issues

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/attendance/components/attendanceFormBuilder.test.tsx
Improve the Add Attendance Form UI to align with the design of other Add Form
=> Enhance  attendance form

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(auth)/login/components/Login.tsx, src/app/(dev)/playground/components/AddDevUserForm.tsx, src/app/(dev)/playground/components/UpdateDevUserForm.tsx, src/app/api/cron/funds/route.ts
This PR implements a cron job that will automatically identify active members  and add active all members with zero payments to the Fund list.
https://www.loom.com/share/c220b574b12b4e1d9683619aa7de4d3b?sid=e120b330-8e03-4cde-b44d-c77469c06cac
=> Create Cron Job to Add All Members to Fund

src/app/(app)/funds/components/FundsList.tsx, src/app/(app)/members/components/MemberList.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/app/(app)/missing-shoes/page.tsx, src/app/layout/components/Sidebar.tsx
Fix consistency No Data Found text in all tables in case of no data found
* Added conditions in all tables  
* Added `No Found Data` in all tables in case of no data found
=> Added No Data found text in all tables

src/app/(app)/dashboard/components/AddMemberCard.tsx, src/app/(app)/dashboard/components/Dashboard.tsx, src/app/(app)/funds/page.tsx, src/app/(app)/leaves/actions/get-all-leave-requests.ts
This PR includes add member card to dashboard where user can navigate to add member form and check  for active members leave request will only display.
* `AddMemberCard.tsx`
=> feat(ticket#458): Add member card in dashboard

src/app/(app)/attendance/components/AttendanceDetails.tsx, src/app/(app)/attendance/components/AttendanceList.tsx
Show detail page on row click in attendance table
=> Show detail page on row click in attendance table

src/app/(app)/attendance/actions/getAttendance.ts, src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/members/edit/[id]/page.tsx, src/common/Actions/getEditPermissions.ts, src/middleware.ts
- Add date column in attendance table
- add validation in the edit route of the member so that shift incharge or member can not update other users data
- Add date column in attendance table
- Add validation in the edit member route
=> Added date column in Attendance and also validation of edit member route

src/app/(app)/attendance/actions/update-attendance.ts, src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/funds/actions/update-fund-details.ts, src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(app)/leaves/actions/updated-leave-request.ts, src/app/(app)/leaves/add/components/LeaveRequestFormBuilder.tsx, src/app/(app)/members/actions/update-user.test.tsx, src/app/(app)/members/actions/update-user.ts, src/app/(app)/members/components/MemberFormBuilder.tsx
- update code for permission for users 
* add conditions on edit routes so that user with specific rules  can  not access specific routes
=> updated code Structure for route permission

src/app/(app)/funds/components/FundsHeader.tsx, src/app/(app)/missing-shoes/add/components/MissingShoesFormBuilder.tsx, src/app/(app)/missing-shoes/components/MissingShoesHeader.tsx, src/app/(app)/missing-shoes/components/MissingShoesReportDetails.tsx, src/common/DateTimePicker/DateTimePicker.tsx
- Fixed search input button animation and full width issue on mobile in Missing Shoes.
- Removed horizontal scroll in mobile design for details view.
- Disabled future dates in the calendar and added max length validation to Description field in Missing Shoes to prevent scripting attacks.
https://www.loom.com/share/45361d54df654742a2374f810ca7adff?sid=7b4a77bb-5a6b-4a98-86b7-ad229c7e1ea1
=> fix(ticket#472) Missing shoe and fund module fixes

src/app/(app)/attendance/actions/update-attendance-digest.tsx, src/app/(app)/attendance/review/components/AttendanceReview.tsx, src/lib/db.tsx, src/types/index.tsx
This PR Implemente a server action to update an existing digest based on its ID or create a new one if it doesn't exist.
* `update-attendance-digest.tsx`
* `AttendanceReview.tsx`
* `AttendanceReviewAction.tsx`
https://www.loom.com/share/db1e939ff1ff40f4b7e0decd6ac0668f?sid=781c813b-d745-416d-83f9-8887c760acf3
=> feat(ticket#469):Add server action to update or create digest by ID

src/app/(settings)/settings/page.tsx, src/app/(settings)/settings/profile/components/Profile.tsx, src/app/(settings)/settings/profile/page.tsx, src/app/layout/components/Sidebar.tsx, src/middleware.ts
- Funds not showing in sidebar & also shift incharge is not going to funds route
- Address input replaced with text area in setting page
=> Fund not showing

src/app/(app)/attendance/components/AttendanceList.tsx, src/app/(app)/leaves/components/LeavesRequestList.tsx, src/app/(app)/members/components/MemberList.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/components/ui/table.tsx
Fixed table cursor issue in all tables
=> Fixed table cursor issue

src/app/(app)/attendance/components/AttendanceDetails.tsx, src/app/(app)/leaves/components/LeaveRequestDetails.tsx, src/app/(app)/members/components/MemberDetails.tsx, src/app/(app)/missing-shoes/components/MissingShoesReportDetails.tsx, src/common/CardWrapper.tsx
- Created card wrapper & and also implemented in details page
=> Created card wrapper

src/app/(app)/dashboard/components/Dashboard.tsx, src/app/(app)/dashboard/components/DashboardHeader.tsx
- Added dashboard header 
- Fixed  card container margin issue
=> Added dashboard header

src/app/(app)/members/actions/get-user-by-id.ts, src/app/error.tsx, src/global-error.tsx
Add Common Error Page for the app
*Added error.tsx file for whole app
=> feat(Members):Added Error Page

src/app/(app)/attendance/components/AttendanceActionRender.tsx, src/app/(app)/attendance/components/AttendanceFormBuilder.tsx
Validation added to ensure start and end times are not the same.
=> Added new validation

src/app/(app)/leaves/actions/createLeaveRequest.ts, src/app/(app)/leaves/actions/updated-leave-request.ts, src/app/(app)/missing-shoes/actions/create-missing-shoes-report.ts, src/app/(app)/missing-shoes/actions/update-missing-shoe-details.ts, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/app/(app)/missing-shoes/components/MissingShoesReportDetails.tsx, src/app/(app)/missing-shoes/details/[id]/page.tsx, src/app/layout/components/Sidebar.tsx, src/common/FormWrapper.tsx
- Update icon for the missing shoes route.
- Add token number with the word `Token no.` in breadcrumbs on the details page.
- Implement loader state during missing shoes search.
- Fix issue with name not displaying in missing shoes details request.
- Improve layout of the leave detail page on tablet view.
=> fix(ticket#476): Fix Missing Shoes  Issues

src/app/(app)/attendance/components/AttendanceDetails.tsx, src/app/(app)/dashboard/components/AddMemberCard.tsx, src/app/(app)/dashboard/components/Dashboard.tsx, src/app/(app)/dashboard/components/LeaveRequestCard.tsx, src/app/layout/components/Sidebar.tsx, src/common/NavigationButton.tsx, src/common/SearchBox/SearchBox.tsx
- Fixed Funds render 2 times in side bar 
- Fixed ui issues in different pages
=> Fixed funds render issue

src/app/(app)/funds/components/FundsList.tsx, src/app/(app)/members/components/MemberActionRender.tsx, src/app/(app)/members/components/MemberList.tsx, src/app/(app)/members/components/MemberStatusFilter.tsx, src/app/layout/PageLayout.tsx, src/common/NoDataFound.tsx, src/components/ui/table.tsx
* Removed scroll from the `No Data Found` component 
* Loading state is missing in funds when we search 
* Alignment of the amount of the funds is not good 
* when there is no data in the archieved or active members then drop down is not appearing which is not good 
* Removed Scroll from the `No Data Found` component 
* Add Loader in the FundsList 
* Update text alignment of amount
* Update condition in the member list so that dropdown can be shown
=> fix:Updated Member List UI and add loader in the fund route

src/app/(app)/attendance/actions/getAttendanceById.ts, src/app/(app)/attendance/edit/[id]/page.tsx, src/app/(app)/funds/components/FundFormBuilder.tsx, src/app/(app)/leaves/actions/get-leave-request-by-id.ts, src/app/(app)/missing-shoes/actions/get-missing-shoe-by-id.ts
Fixed the issue to prevent accessing found missing shoes, approved attendance, and leave status via the URL when viewing or editing their details.
https://github.com/user-attachments/assets/00ceb9ea-62ee-4942-81f2-f07c18da8728
=> Fixed accessing through url  issues

src/app/(app)/leaves/components/LeavesRequestList.tsx, src/app/(app)/leaves/details/[id]/page.tsx, src/app/(app)/leaves/edit/[id]/page.tsx
- Fixed attendance table date format doesn't match other routes issue
- Fixed accessing member leave details via URL by entering member ID issue
=> Fixed date formate issue

src/components/ui/table.tsx
- table is not scrolling properly 
* removed overflow property from the table route
=> fix:removed scroll issue

src/app/(app)/notification/components/NotificationContainer.tsx, src/app/(app)/notification/components/NotificationLayout.tsx, src/app/(app)/notification/page.tsx, src/app/layout/components/Sidebar.tsx, src/middleware.ts
- Notifications Routes should be responsive
* Add conditions on the layout and container of the notifications for making responsiveness
- On Desktop
- On Mobile
- On Tablet
=> feat(Notification):worked on resposivness of Notification Route

next.config.mjs, package.json, src/app/(app)/attendance-report/actions/get-attendance-report-pdf.ts, src/app/(app)/attendance-report/components/DateFilter.tsx, src/app/(app)/attendance-report/components/PdfViewer.tsx, src/app/(app)/attendance-report/page.tsx, src/app/(app)/attendance/page.tsx, src/app/(app)/digest/actions/get-monthly-digest.ts, src/app/(app)/digest/components/DigestReviewsFilter.tsx, src/app/api/cron/notifications/notify-monthly-attendance-report/MonthlyReportPdf.tsx, src/app/api/cron/notifications/notify-monthly-attendance-report/route.tsx, src/app/layout/PageLayout.tsx, src/app/layout/components/Sidebar.tsx, src/middleware.ts, vercel.json, yarn.lock
This PR addressing the implements the following components for the attendance report functionality:
DateFilter: Allows users to select a specific month and year for the attendance report.
AttendanceReportList: Displays the filtered attendance report data.
PdfViewer: Renders the generated attendance report PDF.
get-attendance-report-pdf: Backend function to fetch the attendance report PDF from Supabase storage.
Added DateFilter component.
Updated attendance-report/page.tsx to implement the filtering and rendering logic.
Integrated Supabase storage for PDF retrieval.
=> fix: Monthly Attendance Report

src/components/ui/table.tsx
This PR addressing a UI fix, perviously table content was overflowing form table on mobile screen, Now i have fixed
=> fix:Table overfolw

src/app/api/cron/notifications/notify-monthly-attendance-report/MonthlyReportPdf.tsx, src/app/globals.css
This PR addressing update where I have just update the style of PDF.
=> fix: Updated PDF Syle 

src/app/(app)/notification/actions/get-notifications-count.ts, src/app/(app)/notification/components/NotificationLayout.tsx, src/app/(app)/notification/page.tsx, src/app/layout.tsx, src/components/ui/table.tsx
- fix notifications layout scroll issue 
* fixed notifications layout scroll issue
=> fix:Fixed Notifications Layout issues

src/app/(app)/attendance/components/AttendanceFormBuilder.tsx, src/app/(app)/missing-shoes/components/MissingShoes.tsx, src/common/TimeFormate/12HourFormate.tsx
Create 12 hours time format and use in attendance table
=> create time formate
